### ISSUE TITLE
15$ Adicional tarjeta

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#16]
cuando se genera una tarjeta nueva y se entrega el tríptico el alumno paga 15 pesos por única vez. Hoy por hoy los profes lo ponen en comentarios, porque no es de ningún plan específico. Lo ideal sería que cuando vayan por tarjeta nueva ademas del plan elegido se sumen los 15 pesos. Habría que poner algún carteote para que se acuerden de cobrarlo, más allá que les va a aparecer en su plata a rendir.

**Comment by bcardiff** [comment]
Esto ya se hace al poner que el alumno es nuevo.

Notar que no se está registrando gasto por entregar una nueva tarjeta.
Tampoco hay forma de cambiar la tarjeta de un alumno. Sí asociar una a alguien que no tiene tarjeta.

**Comment by manuelbicain** [comment]
O sea qe cual sería la mejor opción si alguien pierde la tarjeta?
El El sáb, 20 jun 2015 a las 19:07, Brian J. Cardiff <
notifications@github.com> escribió:

> Esto ya se hace al poner que el alumno es nuevo.
>
> Notar que no se está registrando gasto por entregar una nueva tarjeta.
> Tampoco hay forma de cambiar la tarjeta de un alumno. Sí asociar una a
> alguien que no tiene tarjeta.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/16#issuecomment-113826411>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
Por ahora molestar a brian. :-)

Te puedo permitir editar la tarjeta sin drama. Bajo tu propio riesgo. La tarjeta del alumno es 1 sola. Si la cambias, estoy por ahora perdiendo rastro de de quien era.

Al cambiarla le pensas cobrar algo?

**Comment by manuelbicain** [comment]
No se puede hacer update de todos los movimientos con ese número?
El El sáb, 20 jun 2015 a las 20:03, Brian J. Cardiff <
notifications@github.com> escribió:

> Por ahora molestar a brian. :-)
>
> Te puedo permitir editar la tarjeta sin drama. Bajo tu propio riesgo. La
> tarjeta del alumno es 1 sola. Si la cambias, estoy por ahora perdiendo
> rastro de de quien era.
>
> Al cambiarla le pensas cobrar algo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/16#issuecomment-113836948>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
Los movimientos quedan asociados al alumno. Eso no es drama.
Pero si tenia la tarjeta 100, la perdí y después me asignas la 200. No queda en casi ningún lugar que la 100 era mia. Salvo en logs.

Si eso está bien, te dejo cambiar el número de tarjeta.
