### ISSUE TITLE
Colectores no profesores

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#17]
el tema es que en la sede caballito tenemos un caso especial. Porque los que cobran y toman presente son las personas del lugar. Y esta es la peor parte, ahí vamos a porcentaje. O sea que la plata que juntan nos dan solo una parte. Estimo yo que podemos crear un profesor que sea "caballito" , pero nos va a desbarajustar todo después en las finanzas.
Perdón, Juani arreglo esto cuando. O estábamos y que me quedo fuera de scope.

**Comment by bcardiff** [comment]
@manuelbicain, No debería ser alreves? Que igual el que colecte y toma lista sea uno de los profes y les deje cierto porcentaje al lugar?

No veo por qué la gente de caballito va a tomar lista.

Modelarlo se modela, pero definamos quien va a hacer la carga de presentes para ahí definir como lo hago.

**Comment by manuelbicain** [comment]
Es que justa,ente el lugar quiere tener el control. Y tenemos el problema
que la gente tienen que dar doble presente. La gente del lugar está
dispuesta a usar el sistema.
El El dom, 31 may 2015 a las 23:43, Brian J. Cardiff <
notifications@github.com> escribió:

> @manuelbicain <https://github.com/manuelbicain>, No debería ser alreves?
> Que igual el que colecte y toma lista sea uno de los profes y les deje
> cierto porcentaje al lugar?
>
> No veo por qué la gente de caballito va a tomar lista.
>
> Modelarlo se modela, pero definamos quien va a hacer la carga de presentes
> para ahí definir como lo hago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/17#issuecomment-107288434>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
Oka, lo usarian via web o desde el celular también?

Si la plata se la dan al primer profesor de la lista al momento de irse, entonces podemos hacer que al entrar un dato por una clase de ese lugar se descuenta automaticamente.

Y no hay que hacer cambios al formulario.

Pero no traqueamos cuánta plata se fue llevando el lugar, ok?

Y qué pasa con el pago de los $15 o de los packs en ese lugar? Todo TODO es a comisión? Cuánto?

**Comment by manuelbicain** [comment]
Lo usarían vía web. Y que carguen la tarjeta a mano. Esto me lleva aun
nuevo issue. Que pasa si el Fucking alumno se olvida la tarjeta y....
También se olvida el numero?
La plata no estoy seguro cuando se la dan. Ahora lo hablamos con el lugar.
Si es el caso que se lo dan al momento de irse debería sumarse a la plata
que el profesor tiene que rendir. (Me dicen por cucaracha que se lo dan por
clase al profesor)
Seria lo ideal que no haya cambios en el formulario.
Por ahora no me importa track dar la plata que se lleva el lugar, pero si
la que nos llevamos nosotros.
Los 15$ no deberían estar en el porcentaje porque es para cubrir el costo
de tarjeta y tríptico. La comisión es 70% para nosotros y 30% para el lugar.
Un garrón extra es que tienen un piso de xxx$. (860aprox.) si la primer
clase no se cubre con el 30% los chabones se quedan con ese monto, y le dan
el resto al profesor. Lo cual es un quilombo, que vamos a hablar hoy.

El El lun, 1 jun 2015 a las 11:17, Brian J. Cardiff <
notifications@github.com> escribió:

> Oka, lo usarian via web o desde el celular también?
>
> Si la plata se la dan al primer profesor de la lista al momento de irse,
> entonces podemos hacer que al entrar un dato por una clase de ese lugar se
> descuenta automaticamente.
>
> Y no hay que hacer cambios al formulario.
>
> Pero no traqueamos cuánta plata se fue llevando el lugar, ok?
>
> Y qué pasa con el pago de los $15 o de los packs en ese lugar? Todo TODO
> es a comisión? Cuánto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/17#issuecomment-107510961>.
>
-- 
Manuel

**Comment by manuelbicain** [comment]
Esto esta ya en el issue 20

**Comment by bcardiff** [comment]
duplicate #20
