### ISSUE TITLE
Notas o comentarios a nivel de alumno

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#19]
las notas hoy estan a nivel del formulario.
Normalmente son específicas de un alumno. Habría que ponerlas para cada uno.

**Comment by marielgastiarena** [comment]
No sé si esto va acá pero por otro lado, yo sacaría lo del lector de código de barras. Nadie lo usa!
Y no hay alguna opción de que no aparezcan las notas sí o sí en cada alumno sino que se pueda "desplegar" si es necesario en cada uno? Pregunto, ni idea si se puede algo así.

**Comment by bcardiff** [comment]
La app de celular muestra una cosa a la vez. Mostrar un tilde para luego mostrar el campo de notas si se eligió el tilde es más largo que mostrar el campo de notas directamente.
