### ISSUE TITLE
Consulta de efectivo por profesor

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#2]
- Consulta de efectivo por profesor: la consulta tiene que devolver cuanto efectivo tiene en ese momento el docente luego de cobrar las clases. Idealmente con apertura por clase y un total. Es el dinero que el profesor tiene que rendir y sirve para que puedan llevar un control de lo que tienen. Cuando el profesor rinde el dinero esta consulta debería dar 0.
Nivel A: permite ver todo de todos los profesores.
Nivel B: permite ver todo de todos los profesores.
Nivel C: sólo puede ver el efectivo que tiene su propio usuario. Es decir, el mismo.
Nivel D: no tiene acceso.

**Comment by bcardiff** [comment]
@manuelbicain  Se dispone de un total de dinero por entrar a al caja

![screen shot 2015-05-27 at 3 04 57 am](https://cloud.githubusercontent.com/assets/459923/7829926/a6f089d6-041d-11e5-89f5-fc00f345d133.png)

De ahí un detaller por docente

![screen shot 2015-05-27 at 3 07 58 am](https://cloud.githubusercontent.com/assets/459923/7829929/b4e7a59c-041d-11e5-8843-823db1968bea.png)

Y finalmente un detalle indicando de dónde y cuando proviene la plata que debería rendirse

![screen shot 2015-05-27 at 3 00 42 am](https://cloud.githubusercontent.com/assets/459923/7829805/9bb2a190-041c-11e5-9b63-fd18ee1630a1.png)

En la imagen anterior hay un botón que indica que la plata se entrega y se asienta que pasó a la caja.

Algo más por este lado?

**Comment by manuelbicain** [comment]
Esta perfecto. Lo único que me preocupa es como va a funcionar el total
cuando ingresen por usuario. Porque la idea es que los profesores no pueden
ver el total, sino la parte cita que les corresponde.

**Comment by bcardiff** [comment]
El total no lo van a ver. Verán solo lo equivalente a su bolsillo y la última pantalla.

**Comment by manuelbicain** [comment]
Ok!

**Comment by bcardiff** [comment]
Los docentes ven el detalle de las clases que dieron. Y por consiguiente cuánto recolectó cualquiera de ambos docentes.
Además tienen cuánta plata deberían entregar a la escuela y cuánto le debería pagar la escuela al docente por las clases dada.

![screen shot 2015-05-30 at 4 42 25 am](https://cloud.githubusercontent.com/assets/459923/7896158/4d8983fa-0686-11e5-9430-6d65a43e108c.png)
