### ISSUE TITLE
Soporte de sala que colecta plata

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#20]
Hay salas que van a %.
Usan el sistema web

La plata de la dan al profe. Un porcentaje.
Sin incluir la tarjeta.
Pero con la particularidad que se quedan el 100% hasta llegar a 860 pesos.
Después de eso se quedan el 30

**Comment by manuelbicain** [comment]
Para cuándo podamos tener esto? Así lo hablo con la gente de caballito.
Les tengo que armar un manual a prueba de giles.
El El vie, 5 jun 2015 a las 17:31, Brian J. Cardiff <
notifications@github.com> escribió:

> Hay salas que van a %.
> Usan el sistema web
>
> La plata de la dan al profe. Un porcentaje.
> Sin incluir la tarjeta.
> Pero con la particularidad que se quedan el 100% hasta llegar a 860 pesos.
> Después de eso se quedan el 30
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/20>.
>
-- 
Manuel
