### ISSUE TITLE
Reverso de formularios

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#25]
Conozco lo difícil que es. Pero es alta la probabilidad que envíen cosas mal. Y según Mariel debería poderse. La idea sería poder volver atrás lo que ya impactó un formulario. Idealmente el reversado debería poderse editarse y reprocesar.

**Comment by bcardiff** [comment]
Ahora se pueden deshacer los formularios.

![screen shot 2015-06-23 at 6 11 05 am](https://cloud.githubusercontent.com/assets/459923/8302667/ab58d8c8-196e-11e5-86f6-20ad47d23f1c.png)

No siempre se puede deshacer todo completamente, producto de que la información de un curso puede venir de varios lugares.

Cuando se deshace el formulario, se lo puede editar en ona, actualizar y finalmente reprocesar.

Más adelante se van a poder borrar registros manualmente para terminar de soportar todos los escenarios.

Cosas a tener en cuenta:

* Para revertir el alumno se deben revertir los pagos.
* Para revertir los pagos estos no deben haber sido entregados a la escuela.
* Un alumno se trata de revertir siempre y cuando el formulario ona haya sido el último en enviar la info del usuario. Notar que pueden haber varios formularios que contribuyen a la info de un alumno.
* El presente de los docentes solo se revierte cuando no quedó ningún alumno en el curso.
* Los calculos se propagan también a la las comissiones/seguros de sala
* Los alumnos nuevos/visitantes que no tengan otras actividades registradas son eliminados.
