### ISSUE TITLE
Consulta general de efectivo

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#3]
- Consulta general de efectivo: es la consulta usada para ver el efectivo facturado por la escuela. Debe mostrar el dinero que tiene cada profesor y el dinero que se facturó. Debe tener apertura por clase y totales. Debe poder filtrarse por rango de fechas, clase, estado, etc. ( en el peor de los casos se baja todo y se filtra en un excel)
Nivel A: accede a la consulta.
Nivel B: accede a la consulta.
Nivel C: no tiene acceso.
Nivel D: no tiene acceso.

**Comment by bcardiff** [comment]
@manuelbicain Los pagos son en una clase, pero no son necesariamiente por esa clase. Por ejemplo, con el pack de 2 clases a la semana, pago en una pero voy a otra. No tiene sentido filtrar pagos por clase.
En todo caso eso es directamente la asistencia de alumnos a las clases. 

El dia de mañana hay que descontar los taxi dancers. Pero en principio los pagos no se asocian a una clase.

No me queda claro cuál es el "estado" por el que queres filtrar.

Por el momento se puede ver el total de dinero facturado (caja)

![screen shot 2015-05-27 at 3 04 57 am](https://cloud.githubusercontent.com/assets/459923/7829884/3f3593fe-041d-11e5-8d3c-c65a9e656158.png)

y los movimientos de plata generales

![screen shot 2015-05-27 at 3 05 04 am](https://cloud.githubusercontent.com/assets/459923/7829891/4f870da0-041d-11e5-9e6d-8dac0283b498.png)

**Comment by manuelbicain** [comment]
El tema del efectuó por clase venía más qe nada para poder controlar de qe clase venía la plata en caso de que haya algún faltante. Para rastrearla digamos. Pero para esta consulta como bien decís no es necesario.

El estado del efectivo me refería a si era efectivo rendido o no por el profesor.

Los taxis dancers por ahora no dan presente así que no pasa nada.

**Comment by bcardiff** [comment]
Ahí cambié un poco para que resulte más ameno.

![screen shot 2015-05-28 at 4 53 02 am](https://cloud.githubusercontent.com/assets/459923/7855132/8d1cec92-04f5-11e5-9c12-f085b7ae7ab6.png)

Los numeros de "en mano" y "entregado" son independientes del mes.
Es lógico que el "en mano" acumule y cada tanto baje. Pero el "entregado" solo va a subir. Es la suma de ingresos totales por clases.

En la pantalla siguiente se pueden ver los pagos por fecha dia, clase en la que se entrego, profe y si dicha plata fué entregada o no a.

![screen shot 2015-05-28 at 4 52 50 am](https://cloud.githubusercontent.com/assets/459923/7855135/93af8fba-04f5-11e5-90e3-2d0cecc8b0c1.png)

Creo que estamos por este lado, no?

**Comment by manuelbicain** [comment]
Si. El en mano de los profes esta bien. El problema es con el acumulado de
la escuela. Porque se vuelve irrelevante en el momento que empezamos
apagarle a los profes por ejemplo, o las salas. Más aún si no esta filtrado
por mes, no podemos ver el ingreso mensual.

Las opciones son aumentar el manejo de caja, pudiendo poner gastos. Lo cual
no se cuanto te puede complicar. O poder verlo por mes. Esto último es para
que al ver cuanto le falta entregar a los profesores, sabemos cuanto
efectivo realmente tenemos y cuanto esta dando vueltas en ese período.

Si el detalle de pagos se puede bajar a Excel lo podemos explotar
igualmente.

Esta buenísimo Bri.

**Comment by bcardiff** [comment]
Ahora los ingresos se filtrar por mes. Figuran en el mes en que la plata fue entregada del profesor a swing city. No necesariamente es la fecha en al que el alumno le pagó al profesor.

De igual manera con los gastos que representan el salario del docente.

Por ahora registrar todos los movimientos de swingcity no creo que tenga sentido. Mejor extraer esos datos por mes para tener manejar un balance por otro lado.

Los listados se pueden exportar a excel.
Hay soporte limitado de búsqueda y ordenamiento pero se puede ir refinando.
