### ISSUE TITLE
Agregar opción al tomar asistencia de entregar una nueva tarjeta

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#33]
Cuando un alumno pierde la tarjeta, se le puede entregar una sin costo alguno al tomarle asistencia.
En este caso, debería marcarse como una opción. Además de 
* alumno con tarjeta 
* alumno nuevo 
* visitan (sin tarjeta)

debería agregarse una opción de 
* nueva tarjeta por pérdida

En este caso se pide el email del alumno como identificación
El sistema anota el nuevo número de tarjeta y almacena el viejo para no perder la vinculación de que cierta tarjeta fué de él.

**Comment by bcardiff** [comment]
@marielgastiarena así me imagino que se podría soportar el escenario dónde un alumno perdió la tarjeta y se le entrega una nueva.
En este caso no hay costo por entregar una tarjeta, correcto?
Te parece bien que la identificación sea mediante email?

**Comment by marielgastiarena** [comment]
Ahora entiendo! Sí hay costo. Cuando la pierden pagan los $15 de nuevo. Y la identificación puede ser por mail, si.

**Comment by bcardiff** [comment]
Ah, entonces hago que la opción de alumno nuevo sirva para entregar nuevas tarjetas a alumnos existentes. Que pida nombre, apellido, email. Se busca el alumno por el mail y se actualizan  el nombre/apellido en caso de que se indique alguno.

**Comment by marielgastiarena** [comment]
Dale, perfecto.
