### ISSUE TITLE
Agregar plan de pago de 3xSemana $550

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#34]
Los alumnos pueden tomar 3 clases por semana durante un mes

**Comment by bcardiff** [comment]
Como el valor coincide con el pack de 1 clase x semana durante 3 meses, es complicado soportar pagos parciales y que el sistema se dé cuenta que tiene cierto pack habilitado :-(.

**Comment by marielgastiarena** [comment]
Hay que cambiar el precio? Por ahí podría salir $500 3xsem. Tiene sentido que sea más barato que el pack de 3 meses.

**Comment by bcardiff** [comment]
El escenario molesto es que a veces los alumnos hacen pagos parciales.
Te doy $100 una semana. Te dos $150 la otra. Y entonces seria bueno que el sistema se dé cuenta que se otorgó el pack de $250. Si hay más de un pack con el mismo precio el sistema no puede decidir eso. De ahí la complicación.

La otra sería que en el caso de montos parciales se indique qué pack está queriendo comprar. Pero es complicar el formulario me parece.

**Comment by marielgastiarena** [comment]
Claro. Bueno, cambiemos los precios y listo. No compliquemos el formulario.
