### ISSUE TITLE
Mail automatico ante pagos

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#38]
La idea no es un recibo, pero sí un mail agradeciendole por formar parte, o bien por seguir formando parte, y de paso explicar hasta cuándo pueden recuperar la clase.

**Comment by bcardiff** [comment]
Y ya que estamos, cuál es la política de "hasta cuándo pueden recuperar la clase." ?

**Comment by manuelbicain** [comment]
Buena pregunta. Es una de las funciones del mail, para que no queden dudas.
Las realidad es que la clase la pueden recuperar en la duración del pack. O
sea. Termina el mes, en gral, y fueron. O en el caso de los tres meses,
terminan los tres meses y fueron.

2015-06-29 15:14 GMT-03:00 Brian J. Cardiff <notifications@github.com>:
