### ISSUE TITLE
Alumnos que registren presentes no respaldados por un pago

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#4]
Alumnos que registren presentes no respaldados por un pago. Esto es obviamente para detectar cobros no ingresados, planes equivocados, formularios no enviados, alumnos despistados, etc. La formula seria que el alumno no puede tener mas presentes de los que le cubre el dinero registrado (rendido o no por el profesor) . Recordar que los planes vencen en el mes. Es decir que un pago de plan mensual registrado en Marzo sirve solo para Marzo. Y así también para los trimestrales, los tres meses empiezan a contar desde el mes de pago. La consulta tiene que tener filtro por fecha y en lo posible como default el mes actual.
Nivel A: accede a la consulta.
Nivel B: accede a la consulta.
Nivel C: no tiene acceso.
Nivel D: no tiene acceso.

**Comment by marielgastiarena** [comment]
A esto hay que ponerle un número máximo de presentes. 
$250 son 4 clases. 
$300 son 5 clases
$350 (2xsem) pueden ser 10 clases por si tienen 5 clases. (che, es muy barato eso! creo que hay que subir este precio)
$550 (3xsem) 15 clases como máximo dentro del mes
$550 (3 meses) sólo 5 clases por mes como máximo. Podemos cambiar el precio si es necesario.

**Comment by bcardiff** [comment]
Los packs ya indican cantidad de clases por semana y duración del pack en meses.
De ahí se deduce un numero máximo de clases. Por qué te imaginas tener que indicar uno?

**Comment by marielgastiarena** [comment]
Digo, para adentro. Porque supuestamente el pack de 2xsem por ejemplo son 8 clases, pero hay meses de 9 clases y bueno, no pasa nada. O al menos siempre fue así. Lo mismo cuando pagás 3 meses. No son estrictamente 12 clases, sino la clase que toman, 3 meses. Por eso pueden llegar a ser 15. Lo que quiero decir es que debería saltar en el sistema recién si toman más clases que eso.

**Comment by manuelbicain** [comment]
Sólo pienso en como reconocer cuando los profes ingresan un mes de 5
clases.
Pero si lo resuelve esta ok.
El El vie, 26 jun 2015 a las 02:35, marielgastiarena <
notifications@github.com> escribió:

> Digo, para adentro. Porque supuestamente el pack de 2xsem por ejemplo son
> 8 clases, pero hay meses de 9 clases y bueno, no pasa nada. O al menos
> siempre fue así. Lo mismo cuando pagás 3 meses. No son estrictamente 12
> clases, sino la clase que toman, 3 meses. Por eso pueden llegar a ser 15.
> Lo que quiero decir es que debería saltar en el sistema recién si toman más
> clases que eso.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/4#issuecomment-115524676>.
>
-- 
Manuel
