### ISSUE TITLE
Tener un profesor que sea "otros"

### ISSUE THREAD

**Issue by marielgastiarena** [bcardiff/themis#40]
Esto es porque tenemos reemplazos, que toman asistencia, pero no son ningun profesor oficial.

**Comment by bcardiff** [comment]
Cuando hay un reemplazo, no se le paga al oficial y si al reemplazo, no?

Si es así, basta con que se pongan como profesor. Que incluso puede juntar la plata.
No hay conocimiento por el sistema de que *es un reemplazo*.

No entiendo qué necesitan en la situación donde es un reemplazo.

**Comment by bcardiff** [comment]
@marielgastiarena me explicás?

**Comment by manuelbicain** [comment]
Es solo para que el presente no le vaya a uno de los profesores oficiales
digamos.


El dom., 5 jul. 2015 a las 21:21, Brian J. Cardiff (<
notifications@github.com>) escribió:

> @marielgastiarena <https://github.com/marielgastiarena> me explicás?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/40#issuecomment-118682310>.
>
-- 
Manuel
