### ISSUE TITLE
Rendicion parcial de los profesores

### ISSUE THREAD

**Issue by marielgastiarena** [bcardiff/themis#41]
Ahora los profesores pueden rendir todo o nada. Hay casos en los que dan un monto de plata que no es el total.

**Comment by bcardiff** [comment]
Si el objetivo es entregar plata que no coincide con el total, entonces #42 lo cubre.

Pero si la idea es entregar la recaudación de una semana, pero no de la otra, seria otro tema.

En qué contexto un docente quiere entregar parte de la caja chica que maneja en lugar de toda?

**Comment by bcardiff** [comment]
@marielgastiarena me confirmas si esto es necesario o si con #42 estámos?

**Comment by manuelbicain** [comment]
Yo creo que sí.

El jue., 2 jul. 2015 a las 23:01, Brian J. Cardiff (<
notifications@github.com>) escribió:

> @marielgastiarena <https://github.com/marielgastiarena> me confirmas si
> esto es necesario o si con #42
> <https://github.com/bcardiff/themis/issues/42> estámos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/41#issuecomment-118210595>.
>
-- 
Manuel

**Comment by manuelbicain** [comment]
Ahi hice una prueba. Creo que no es exactamente lo que necesitamos. Creo
que hice cagada. Ejemplo. Yo tenía que rendir 1560 pesos de junio. Pero
como ya hice una clase de Julio me aparecía para rendir más plata. Hice la
prueba de poner 1560 y rendirlo, pero por lo que me doy cuenta ahora me
desapareció toda la deuda, y debería haberme quedado. Lo que imagino como
escenario ideal, aunqeu se que es delirante es poder seleccionar que cosas
se están cancelando con este pago.

El vie., 3 jul. 2015 a las 4:52, Manuel Ignacio Bicain Goral (<
manuelbicain@gmail.com>) escribió:

> Yo creo que sí.
>
> El jue., 2 jul. 2015 a las 23:01, Brian J. Cardiff (<
> notifications@github.com>) escribió:
>
>> @marielgastiarena <https://github.com/marielgastiarena> me confirmas si
>> esto es necesario o si con #42
>> <https://github.com/bcardiff/themis/issues/42> estámos?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bcardiff/themis/issues/41#issuecomment-118210595>.
>>
> --
> Manuel

-- 
Manuel

**Comment by bcardiff** [comment]
Hay $570 que quedaron como no rendidos, aunque están los pagos de los alumnos. Podés verlo en 'Entregados a Swing City' en http://app.swingcity.com.ar/admin/teacher_cash_incomes.

Puedo revertir esas 3 primeras lineas. Querés?

Para hacer pruebas y jugar y probar está stg.swingcity.com.ar chicos ;-) siempre esos datos no importan y cuando quieran podemos hacer copia del app. a stg. si necesitan.

Es medio incómodo que "marquen" los pagos de alumnos que quieren rendir y además decir cuánto rinden. Porque a la hora de rendir tienen tanta plata que no saben bien de dónde vino. Para mí saben si es toda la plata de la caja chica o no.    No se me ocurre si se juntan para hacer la transacción, por qué no entregarian toda la plata.

Se me ocurre que las alternativas son:
1) Que la rendición de plata sea en función de la recaudación por mes. O sea, el profe tiene separada la caja chica en función del mes.

o

2) A la hora de indicar el monto que se entrega, también se marca el monto que se quedan. Como para que no quede en cero. Pero sin marcar me quedo plata de Fulano o Mengano.

Pero insisto, no termino de entender por qué no entregan *toda* la caja chica.

**Comment by manuelbicain** [comment]
Perdón por la prueba. Creí que estaba claro y no pense en probar en stg.

Hay posibilidades de que no rindan todo porque simplemente no lo tienen.
Pero más probable es por lo que te decía que hay un desfasaje entre
registración y pago. O sea, el profesor nos da la plata mientras damos
clase, y se va a dar su clase. Cobra a los alumnos de esa clase nueva, pero
ya nos rindió la plata vieja. Cuando queremos regstras falta plata.
Creo que la opción más clara es rendir por mes, porque así nos dan la plata
en la realidad. Pero poniendo el monto como hoy para ajustar diferenciaas.

El vie., 3 jul. 2015 a las 11:54, Brian J. Cardiff (<
notifications@github.com>) escribió:

> Hay $570 que quedaron como no rendidos, aunque están los pagos de los
> alumnos. Podés verlo en 'Entregados a Swing City' en
> http://app.swingcity.com.ar/admin/teacher_cash_incomes.
>
> Puedo revertir esas 3 primeras lineas. Querés?
>
> Para hacer pruebas y jugar y probar está stg.swingcity.com.ar chicos ;-)
> siempre esos datos no importan y cuando quieran podemos hacer copia del
> app. a stg. si necesitan.
>
> Es medio incómodo que "marquen" los pagos de alumnos que quieren rendir y
> además decir cuánto rinden. Porque a la hora de rendir tienen tanta plata
> que no saben bien de dónde vino. Para mí saben si es toda la plata de la
> caja chica o no. No se me ocurre si se juntan para hacer la transacción,
> por qué no entregarian toda la plata.
>
> Se me ocurre que las alternativas son:
> 1) Que la rendición de plata sea en función de la recaudación por mes. O
> sea, el profe tiene separada la caja chica en función del mes.
>
> o
>
> 2) A la hora de indicar el monto que se entrega, también se marca el monto
> que se quedan. Como para que no quede en cero. Pero sin marcar me quedo
> plata de Fulano o Mengano.
>
> Pero insisto, no termino de entender por qué no entregan *toda* la caja
> chica.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/41#issuecomment-118367999>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
Sinó podemos hacer que se indique una fecha limite y entonces se muestran/entregan los pagos con respecto a esa fecha. En el caso que planteas seria hasta el dia antes a dar la clase. Hacemos esto?

**Comment by manuelbicain** [comment]
Como sería eso? Les ponen hasta que fecha están rindiendo digamos?

El vie., 3 jul. 2015 a las 15:24, Brian J. Cardiff (<
notifications@github.com>) escribió:

> Sinó podemos hacer que se indique una fecha limite y entonces se
> muestran/entregan los pagos con respecto a esa fecha. En el caso que
> planteas seria hasta el dia antes a dar la clase. Hacemos esto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/41#issuecomment-118405090>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
En páginas como http://app.swingcity.com.ar/admin/teachers/1/owed_cash apareceria por defecto plata al dia de "hoy" pero pudiendo cambiar ese hoy por cualquier fecha. Entonces desaparecerian los moviemientos desde la fecha indicada hasta la actual. Uno pondria como fecha, el momento en que se juntó con el docente a hacer la transacción ;-) .

Además se informa cuánto se le entrego y se transfieren los movimientos en cuestión

**Comment by manuelbicain** [comment]
Joya. Y eliminemos lo que cargué ayer.

El vie., 3 jul. 2015 a las 15:34, Brian J. Cardiff (<
notifications@github.com>) escribió:

> En páginas como http://app.swingcity.com.ar/admin/teachers/1/owed_cash
> apareceria por defecto plata al dia de "hoy" pero pudiendo cambiar ese hoy
> por cualquier fecha. Entonces desaparecerian los moviemientos desde la
> fecha indicada hasta la actual. Uno pondria como fecha, el momento en que
> se juntó con el docente a hacer la transacción ;-) .
>
> Además se informa cuánto se le entrego y se transfieren los movimientos en
> cuestión
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/41#issuecomment-118405915>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
Se va a ver así.
Primero indicando la fecha de la transacción, consultando cuánto daria en total y pudiendo corregir ese monto.

<img width="1051" alt="screen shot 2015-07-05 at 2 47 01 pm" src="https://cloud.githubusercontent.com/assets/459923/8512684/c7b2449a-2324-11e5-9f09-c59a9c511536.png">

**Comment by bcardiff** [comment]
@manuelbicain @marielgastiarena  esto ya está para que lo usen y arreglé los datos que pidió manu.

**Comment by manuelbicain** [comment]
Voy a probar en tsg antes
El El dom, 5 jul 2015 a las 15:16, Brian J. Cardiff <
notifications@github.com> escribió:

> @manuelbicain <https://github.com/manuelbicain> @marielgastiarena
> <https://github.com/marielgastiarena> esto ya está para que lo usen y
> arreglé los datos que pidió manu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/41#issuecomment-118646930>.
>
-- 
Manuel
