### ISSUE TITLE
Ajuste de monto de profesores

### ISSUE THREAD

**Issue by marielgastiarena** [bcardiff/themis#42]
Todavia los profesores comenten errores en la plata que juntan y la que registran. Entonces por ejemplo tienen 100 pesos mas. De alguna manera seria ideal poder cargar estas diferencias para que la contabilidad sea mas real. No es prioritario.

**Comment by manuelbicain** [comment]
Tal vez sea un poco prioritario.

**Comment by bcardiff** [comment]
Me parece bien que empecemos a usar esta funcionalidad del sistema. Está para eso.
Podemos hacer que en la pantalla de rendir plata, se pueda poner un monto corregido. A efectos de llevar la contabilidad. Pero hace ruido que haya diferencia.

Si entregan plata de más, es que a algún alumno no se le anotó el pago. Va a saltar en algún momento, cuando la clase no esté validada por un pago, y ahí qué hacen? Le darian de alta un pack/pago al alumno? Pero sin afectar la contabilidad.

Si entregan plata de menos, quiere decir que imputaron algún pago de más. Acá no hay mucho que hacer :-P Alguien se llevó de arriba plata.

O simplemente se mandaron moco con los vueltos o mezclaron plata de ellos con la del sistema. Ahí es un problema de la realidad.

¿Les parece bien encarar una solución por estos lados?

**Comment by manuelbicain** [comment]
Otro tema que ya hablamos son los gastos. Por eso los profesores entregarían menos. Es posible incluir lo que hace la planilla al modelo? Creo que era tu idea. No es más que un abm de plata, causa, y si ya se devengó de la plata de SWING CITY.

Veamos los escenarios.
Si les da de más, va a saltar. Aparece un nuevo issue, de cómo corregir pagos efectuados pero no registrados. Creo que tendría que poder asignarse un pack para que luego no de error el control de presente contra pago. De esto se desprende que la diferencia pudo o no se registrada/corregida. De alguna manera el arreglo debería poder asociarse al profesor/fecha/clase, pero solo para poder ver que la corrección ya está respaldada por la realidad.

Si entregan plata de menos es porque algo hicieron mal. Por ejemplo, se olvidaron de cobrar, la perdieron, o algo. No imagino una excusa para que no rindan todo.

Cuando salten los problemas vamos a ver... como alumnos que digan que pagaron y no haya registrado pago. Por eso el mail de confirmación por ahí está bueno.

**Comment by bcardiff** [comment]
La parte de cargar un pack la puse en el #46.

Ahora al registrar la entrega de plata se puede indicar el valor entregado

<img width="505" alt="screen shot 2015-07-02 at 10 52 18 pm" src="https://cloud.githubusercontent.com/assets/459923/8491340/244c011a-210d-11e5-85bb-ce9f535b7efb.png">

Luego aparece la diferencia como un "Ajuste de Saldo" en el histórico. Ya sea negativa (se rindió menos plata) o positiva (se rindió más plata).

<img width="1202" alt="screen shot 2015-07-02 at 10 52 29 pm" src="https://cloud.githubusercontent.com/assets/459923/8491341/28a96950-210d-11e5-8b44-941f0903d386.png">

Notar que marcan todas las entradas como entregadas a la escuela. O sea, el docente vacía su caja chica.
