### ISSUE TITLE
Pagos Parciales

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#44]
A la hora de pagarle a los profes, también es de todo o nada.
Ende cuando hacemos los numeros, en gral el profe ya dio su primer clase del mes siguiente. Y cuando le queremos pagar y registrarlo, descontariamos también esa primer clase.

**Comment by bcardiff** [comment]
Esto se podría contemplar poniendo botones de pago por mes. ¿Alcanza?

**Comment by manuelbicain** [comment]
Si. Sólo hay que ser prolijos en los presentes.
El El jue, 2 jul 2015 a las 09:56, Brian J. Cardiff <
notifications@github.com> escribió:

> Esto se podría contemplar poniendo botones de pago por mes. ¿Alcanza?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/44#issuecomment-118023367>.
>
-- 
Manuel

**Comment by bcardiff** [comment]
Para ser consistente, hice lo mismo que para la entrega de dinero. Se indica las clases hasta qué dia se quieren pagar, se ve el resumen y se elige marcarlas como pagas.

<img width="877" alt="screen shot 2015-07-05 at 7 23 33 pm" src="https://cloud.githubusercontent.com/assets/459923/8513685/7afcc892-234b-11e5-8a3f-9a4dd49401ee.png">

**Comment by manuelbicain** [comment]
Ok. Yo probé en stg y esta bueno asi
El El dom, 5 jul 2015 a las 19:24, Brian J. Cardiff <
notifications@github.com> escribió:

> Para ser consistente, hice lo mismo que para la entrega de dinero. Se
> indica las clases hasta qué dia se quieren pagar, se ve el resumen y se
> elige marcarlas como pagas.
>
> [image: screen shot 2015-07-05 at 7 23 33 pm]
> <https://cloud.githubusercontent.com/assets/459923/8513685/7afcc892-234b-11e5-8a3f-9a4dd49401ee.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/44#issuecomment-118671672>.
>
-- 
Manuel
