### ISSUE TITLE
Recalculo Cabalito

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#45]
hay que ver el puto cálculo de caballito. Nunca anda bien....

**Comment by manuelbicain** [comment]
Con esto no paso nada no?

**Comment by bcardiff** [comment]
No. aún no. Hay que exponer más info para que no sea obscuro y permitir la carga via web como la de los admines para que no pasen por ona y sea todo directo. Ahí se va a poder analizar más me parece.

**Comment by manuelbicain** [comment]
El tema es que siguen adelante. Y encima se mandan mocos.
El El mar, 14 jul 2015 a las 09:54, Brian J. Cardiff <
notifications@github.com> escribió:

> No. aún no. Hay que exponer más info para que no sea obscuro y permitir la
> carga via web como la de los admines para que no pasen por ona y sea todo
> directo. Ahí se va a poder analizar más me parece.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/45#issuecomment-121230649>.
>
-- 
Manuel
