### ISSUE TITLE
Formularios no enviados

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#5]
Formularios no enviados. Entre principio de mes y la fecha actual debe haber registros para todas las clases que ocurrieron. La consulta debe mostrar fecha y curso del que faltan datos. En caso que el día sea feriado, aparecerá durante todo el mes.
Nivel A: accede a la consulta.
Nivel B: accede a la consulta.
Nivel C: no tiene acceso.
Nivel D: no tiene acceso.

**Comment by bcardiff** [comment]
@manuelbicain si te parece bien cómo aparece ahora, ya podemos cerrar esta historia.
Se ve por mes elegido.
Aparecen en rojo si la clase está faltante.
Y el detalle lo muestra

![screen shot 2015-05-22 at 2 36 06 pm](https://cloud.githubusercontent.com/assets/459923/7776266/09f34c58-0090-11e5-9cf8-17a188e453a7.png)

![screen shot 2015-05-22 at 2 37 02 pm](https://cloud.githubusercontent.com/assets/459923/7776269/0e338c60-0090-11e5-9c71-ce17ff3cc9ab.png)


Si te parece que hay que hacer algo más avisame por acá.

**Comment by manuelbicain** [comment]
Me gusta. Esta bueno. Creo que tiene mucha información de una vista. Eso es
buenísimo.
Veamos como quedan estos puntos.

* calendario para ver las clases que deberian darse
Esto es parametrizable? Digo porque pueden aparecer y desaparecer clases.

* alerta de cuando de una clase no se mandó info
Esta claro. Aparecen en rojo.

* cantidad de docentes y alumnos por clase
Se ve perfecto y al toque. Creo que lo único que le faltaría sería poder
bajar eso a un Excel. Para trabajarlo.

* detalle escueto de los que participaron de la clase
Esta bien creo. Lo único raro es como te trae a los alumnos. Podría ponerse
más información? Como el Mail?

* procesamiento de pagos de alumnos
Estuve jugando un poco. Sólo te cuenta los pagos de alumnos nuevos. No?

* saber cuánta plata tiene cada docenete en mano que debería darle a la
caja de swing city (en detalle por docente y total)
Eso parece estar bien. Tenemos que ver como registrar la rendición.

Jugando pienso cosas para los formularios.
Es posible que sólo aparezcan las clases del día elegido? Tipo sábado?
Con el tema de los profesores, una forma de simplificarlo sería con doble
carga de docente. Una para el que recolecta y un segundo paso para la
pareja. Siendo esto último opcional.

**Comment by bcardiff** [comment]
2015-05-22 21:12 GMT-03:00 manuelbicain <notifications@github.com>:

> Me gusta. Esta bueno. Creo que tiene mucha información de una vista. Eso es
> buenísimo.
> Veamos como quedan estos puntos.
>
> * calendario para ver las clases que deberian darse
> Esto es parametrizable? Digo porque pueden aparecer y desaparecer clases.
>

Si, están en la base. Aún no hay ABM de clases, pero me parece mejor
focalizar en el proceso general. El resto se hace, pero no es crítico. No
cambian todo el tiempo las clases. Ni los docentes.


>
> * alerta de cuando de una clase no se mandó info
> Esta claro. Aparecen en rojo.
>
> * cantidad de docentes y alumnos por clase
> Se ve perfecto y al toque. Creo que lo único que le faltaría sería poder
> bajar eso a un Excel. Para trabajarlo.


 Anotado en #13




> * detalle escueto de los que participaron de la clase
> Esta bien creo. Lo único raro es como te trae a los alumnos. Podría ponerse
> más información? Como el Mail?
>

Si si, la idea es que aparezca una tabla.
Hay algunos detalles sobre si el alumno se encontró o no o si habia alguna
inconsistencia con los datos. Todo eso deberia aparecer en una tabla ahí
donde ahora está el listado escueto.

Pregunta, los alumnos los queres con nombre y por separado el apellido (lo
cual hay que completare en el formulario) o dejamos nombre y apellido junto?


>
> * procesamiento de pagos de alumnos
> Estuve jugando un poco. Sólo te cuenta los pagos de alumnos nuevos. No?
>

Alumnos nuevos
Alumnos visitantes (que no tienen ni van a tener tarjeta)
y en el caso de alumnos existentes, si justamente, existen. Pero eso solo
porque no hice que sea meas robusto.


>
> * saber cuánta plata tiene cada docenete en mano que debería darle a la
> caja de swing city (en detalle por docente y total)
> Eso parece estar bien. Tenemos que ver como registrar la rendición.
>

Yeap, como siguiente voy a empezar a trabajar en los movimientos de cajas,
y por ahora será un botón cualunque en la web, después vemos qué proceso
humano querés que "aprete el botón"


>
> Jugando pienso cosas para los formularios.
> Es posible que sólo aparezcan las clases del día elegido? Tipo sábado?
>

Lo único que se me ocurre es que el usuario diga qué dia de semana es la
clase y eso filtre la lista de clases.

Pero no se puede inferir de la fecha. :-(

Se podría sacar la fecha y dejar dia de semana. Eso haria que solo se
pueden cargar clases 1 semana hacia atrás, salvo quizás especifiquen fecha
opcional.

No estoy seguro qué seria más cómodo.



> Con el tema de los profesores, una forma de simplificarlo sería con doble
> carga de docente. Una para el que recolecta y un segundo paso para la
> pareja. Siendo esto último opcional.
>

O sea, el formulario tiene otro campo de tipo docente. Que representa que
dío la clase pero no se quedó con la plata informada en el formulario. Eso
sí se puede hacer.

**Comment by manuelbicain** [comment]
Bueno. No se cómo poner incomments en esta herramienta. Grrrrr.

- obvio que parametrizar las clases no es prioridad. Me imagine que era parametrizable, pero tenía que preguntar. Je. Tocamos la base y a la lona.

- nombre y apellido. Esto parece una boludez. Pero tenerlos separados facilita mucho al momento de hacer el mailing. Porque tiene campos automáticos.
- el botón en la web para las rendiciones es más que suficiente.
- con el tema de la fecha creo lo dejamos así. 
- y el docente creo que tendría que ser un paso más. Primero el oficial u luego el otro .
