### ISSUE TITLE
Monto Mensual Mal calculado

### ISSUE THREAD

**Issue by manuelbicain** [bcardiff/themis#53]
El monto gral calculado para el mes está mal. No filtra por mes.

**Comment by bcardiff** [comment]
Los de la izquierda, en azul, no se filtran por mes pues son los pendientes a entregar por parte de la escuela o a la escuela. No tiene sentido filtrar por mes.

Los de la derecha, en negro, sí se filtran por mes. Pero se asocian al mes en cual se hizo la transacción docente<->escuela y no por ejemplo alumno<->docente. Ya que es efectivamente cuando la escuela percibe el ingreso/egreso de plata.

**Comment by manuelbicain** [comment]
ME refiero al monto general que aparece en inicio.

**Comment by bcardiff** [comment]
Me refiero a esos. Ya sea para admin o para docente.

**Comment by manuelbicain** [comment]
El de azul esta ok.
El negro creo que no da bien. O no se calcula bien. Entiendo que muestra lo
que se percibió en el mes, más allá del mes al que corresponda. Pero aún
así no da.
El El mar, 4 ago 2015 a las 4:01, Brian J. Cardiff <notifications@github.com>
escribió:

> Me refiero a esos. Ya sea para admin o para docente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/53#issuecomment-127502381>.
>
-- 
Manuel
