### ISSUE TITLE
No se pueden exportar las asistencias de una clase 

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#57]
Ejemplo http://app.swingcity.com.ar/admin/course_logs/423

**Comment by bcardiff** [comment]
@manuelbicain ya está la exportación de asistencias arreglada

**Comment by manuelbicain** [comment]
Brian esta vivo!!!
El El mar, 15 sept 2015 a las 10:11, Brian J. Cardiff <
notifications@github.com> escribió:

> Closed #57 <https://github.com/bcardiff/themis/issues/57> via eab71f0
> <https://github.com/bcardiff/themis/commit/eab71f0d2b7e17a5d36da708bd56480784944395>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcardiff/themis/issues/57#event-409763455>.
>
-- 
Manuel
