### ISSUE TITLE
Poder quitar del listado planes de pago obsoletos

### ISSUE THREAD

**Issue by bcardiff** [bcardiff/themis#67]
El listado de precios está un poco cargado.

Supongo que sería necesario poder marcar como obsoletos algunos planes de pago. O al menos no mostrar aquellos que tiene precio $0.

<img width="650" alt="Screen Shot 2022-03-26 at 18 09 44" src="https://user-images.githubusercontent.com/459923/160257233-4b177cd1-ed60-4ee4-946c-700e28f149e4.png">

Qué planes se muestran se determina en el siguiente lugar:

https://github.com/bcardiff/themis/blob/11bebaf69e928fa4895257bb961a9912d291c215/app/helpers/application_helper.rb#L109-L111

@manuelbicain, opiniones?

**Comment by manuelbicain** [comment]
Sep. Los obsoletos los dejé en 0 pensando en eso.

**Comment by Mar12358** [comment]
Quitar de seeds.rb payment_plan obsoletos. 
Además de eso, entiendo que quieren que los pueda quitar el usuario admin directamente desde la app, en ese caso se podría implementar dsps. simplemente creando una función q acceda a seeds y elimine la línea en cuestión. 
Pero por el momento quitar de seeds. 
@bcardiff está bien lo que estoy pensando?

**Comment by manuelbicain** [comment]
Ojo, entiendo que está corrido el último seeds. Mirá la fecha, lo subió
Javi hace dos meses aprox.

**Comment by manuelbicain** [comment]
Creo que el problema es que si sacamos los packs obsoletos del seeds no te
lo elimina del GLIMS.

**Comment by Mar12358** [comment]
bueno, ahí comenté los packs de afro como prueba, para ver eso...  pusheando a GH se deployea automaticamente? debería verlo reflejado en la web directamente? 
Si no funciona podría usar el método destroy de ActiveRecord en el modelo PaymentPlan, mas adelante igualmente...

**Comment by Mar12358** [comment]
Listo, 
Aparecen los packs que no tienen precio = 0, excepto aquellos cuya descripción incluya "bonif", admite upper/lower case por igual.
Cierro Issue
